Application has thrown an uncaught exception and is terminated:
Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:717:40)
    at Connection.write (G:\STUDY\PROJECT\MEAN\GyanMitra19\GyanMitra19-NodeJs\node_modules\mongodb-core\lib\connection\connection.js:734:57)
    at G:\STUDY\PROJECT\MEAN\GyanMitra19\GyanMitra19-NodeJs\node_modules\mongodb-core\lib\connection\pool.js:1563:44
    at waitForAuth (G:\STUDY\PROJECT\MEAN\GyanMitra19\GyanMitra19-NodeJs\node_modules\mongodb-core\lib\connection\pool.js:1417:40)
    at G:\STUDY\PROJECT\MEAN\GyanMitra19\GyanMitra19-NodeJs\node_modules\mongodb-core\lib\connection\pool.js:1425:5
    at G:\STUDY\PROJECT\MEAN\GyanMitra19\GyanMitra19-NodeJs\node_modules\mongodb-core\lib\connection\pool.js:1278:23
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
